# Generated by Django 4.0.5 on 2022-07-05 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='familiares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('edad', models.IntegerField()),
                ('profesion', models.CharField(max_length=40)),
                ('cuadro', models.CharField(max_length=35)),
                ('fecha_nacimiento', models.DateField()),
            ],
        ),
    ]
